image: node:latest

before_script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl
  - npm install
  - npx patch-package

stages:
  - build
  - production

build:
  stage: build
  script:
    - cp src/configs/config.json.example src/configs/config.json
    - cp src/configs/credentials.json.example src/configs/credentials.json
    - npm run build
    - mv build/configs/config.json build/configs/config.json.example
  artifacts:
    paths:
      - build

production:
  stage: production
  script:
    - cd build
    - cp $BOT_CONFIG_PRODUCTION ./configs/config.json
    - cp $BOT_CREDENTIALS_CONFIG_PRODUCTION ./configs/credentials.json
    - cp $SSH_KEY ./configs/id_rsa
    - >
      echo '{"connection": "process.env.DATABASE_URL", "ssl": true}' > ./configs/database.json
    - dpl --skip-cleanup --provider=heroku --app=$HEROKU_APP_PRODUCTION --api-key=$HEROKU_API_KEY
  only:
    - master
  when: manual